[package]
name = "wm"
version = "0.1.0"
edition = "2021"

[dependencies]
xcb = { version = "1.2.2", features = ["randr"] }
bitflags = "2.4.1"
thiserror = "1.0.50"
slab = "0.4.9"

[[bin]]
name = "ndwm"
path = "src/main.rs"
